### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by dhy1294253770** [H-Designer/Tensorflow-Verification_Code#2]
ModuleNotFoundError: No module named 'nets' 这是什么原因呢？

**Comment by H-Designer** [comment]
你给我你的邮箱，我给你发过去






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dhy1294253770"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 凌晨0:15
收件人:&nbsp;"H-Designer/Tensorflow-Verification_Code"<Tensorflow-Verification_Code@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[H-Designer/Tensorflow-Verification_Code] 代码报错 (#2)




ModuleNotFoundError: No module named 'nets' 这是什么原因呢？

**Comment by dhy1294253770** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好！ 非常感谢您的回复，我的邮箱是Deng_haiyu@163.com
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1294253770
                            
                    
                        
                            
                                    1294253770@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年12月6日 09:58，H-deisgner<notifications@github.com> 写道： 


你给我你的邮箱，我给你发过去



























------------------&nbsp;原始邮件&nbsp;------------------



发件人:&nbsp;"dhy1294253770"<notifications@github.com&gt;;



发送时间:&nbsp;2019年12月6日(星期五) 凌晨0:15



收件人:&nbsp;"H-Designer/Tensorflow-Verification_Code"<Tensorflow-Verification_Code@noreply.github.com&gt;;



抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;



主题:&nbsp;[H-Designer/Tensorflow-Verification_Code] 代码报错 (#2)



















ModuleNotFoundError: No module named 'nets' 这是什么原因呢？



 



—



You are receiving this because you are subscribed to this thread.



Reply to this email directly, view it on GitHub, or unsubscribe.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by H-Designer** [comment]
close
